spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VidhyaChidambaram/
          search-paths: ConfigData
        native:
          search-locations: classpath:/cloud-config

eureka.client.serviceUrl.defaultZone: http://localhost:8010/eureka/
      