server:
  port: 8001
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VidhyaChidambaram/
          search-paths: ConfigData
        native:
          search-locations: classpath:/cloud-config
        